

nodes: "/projects/caeg/data/db/aeDNA-refs/resources/20230825/ncbi/taxonomy/nodes.dmp"
names: "/projects/caeg/data/db/aeDNA-refs/resources/20230825/ncbi/taxonomy/names.dmp"
acc2tax: "/projects/caeg/data/db/mikkels/combined_accession2taxid_20221112.gz"
base: "pmp_output/"
testrun: False 
smdb: "250113.cambodia.megatable.tsv"
finished_libs: "250113.files.csv"